SistemaVenda/SistemaVenda/Models/CategoriaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaVenda.Models
{
    public class CategoriaViewModel
    {
        public int? Codigo { get; set; }

        [Required(ErrorMessage="Informe a Descrição da Categoria!")]
        public string Descricao { get; set; }
    }
}

SistemaVenda/SistemaVenda/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Aplicacao.Servico.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaVenda.Models;

namespace SistemaVenda.Controllers
{
    public class CategoriaController : Controller
    {
        readonly IServicoAplicacaoCategoria ServicoAplicacaoCategoria;

        public CategoriaController(IServicoAplicacaoCategoria servicoAplicacaoCategoria)
        {
            ServicoAplicacaoCategoria = servicoAplicacaoCategoria;
        }

        public IActionResult Index()
        {           
            return View(ServicoAplicacaoCategoria.Listagem());
        }

        [HttpGet]
        public IActionResult Cadastro(int? id)
        {
            CategoriaViewModel viewModel = new CategoriaViewModel();

            if (id != null)
            {
                viewModel = ServicoAplicacaoCategoria.CarregarRegistro((int)id);
            }
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Cadastro(CategoriaViewModel entidade)
        {
            if (ModelState.IsValid)
            {
                ServicoAplicacaoCategoria.Cadastrar(entidade);
            }
            else
            {
                return View(entidade);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Excluir(int id)
        {
            ServicoAplicacaoCategoria.Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

SistemaVenda/SistemaVenda/Views/Categoria/Cadastro.cshtml
@{
    ViewData["Title"] = "Categorias";
}

<h2>Categorias</h2>
<hr />

@model SistemaVenda.Models.CategoriaViewModel

@{
    var disabled = (Model.Codigo == null) ? "disabled" : string.Empty;
}

<form asp-controller="Categoria" asp-action="Cadastro" method="post">
    <input type="hidden" asp-for="Codigo" value="@Model.Codigo" />

    <div class="form-group">
        <div class="col-4">
            <label>Descrição</label>
            <input asp-for="Descricao" type="text" value="@Model.Descricao" class="form-control" />
            <span asp-validation-for="Descricao" class="text-danger"></span>
        </div>
        <br />
        <div class="col">
            <button type="button" class="btn btn-info" onclick="Novo()">Novo</button>
            <button type="submit" class="btn btn-success">Gravar</button>
            <button type="button" class="btn btn-warning" onclick="Listagem()">Listagem</button>
            <button type="button" class="btn btn-danger" onclick="Excluir(@Model.Codigo)" @disabled>Excluir</button>
        </div>
    </div>
</form>

<script>
    function Novo() {
        Request("Cadastro");
    }
    function Listagem() {
        Request("");
    }
    function Excluir(Codigo) {
        Request("Excluir\\" + Codigo);
    }
    function Request(request) {
        window.location = window.origin + "\\Categoria\\" + request;
    }
</script>

SistemaVenda/SistemaVenda/Views/Categoria/Index.cshtml
@{
    ViewData["Title"] = "Categorias";
}

@model List<SistemaVenda.Models.CategoriaViewModel>;

<h2>Categorias</h2>
<hr />

<table class="table table-bordered">
    <thead>
        <tr style="background-color:#f6f6f6">
            <th>Código</th>
            <th>Descrição</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr onclick="Editar(@item.Codigo)" style="cursor:pointer;" >
                <td>@item.Codigo</td>
                <td>@item.Descricao</td>
            </tr>
        }
    </tbody>
</table>
<br />

<button type="button" class="btn btn-block btn-primary" onclick="Cadastrar()">Cadastrar Categoria</button>

<script>
    function Editar(Codigo) {
        window.location = window.origin + "\\Categoria\\Cadastro\\" + Codigo;
    }

    function Cadastrar() {
        window.location = window.origin + "\\Categoria\\Cadastro";
    }
</script>